RUN_N_TIMES: 1
DATA:
  NAME: "CUB"
  NUMBER_CLASSES: 200
  XLSA:
    PROTOCOL_MODE: "final_gzsl"      #dev / final_zsl / final_gzsl
MODEL:
  TYPE: "vit"
  CLASSIFIER: "vspcn_baseline"
  PROMPT:
    ENABLE: True
    BACKEND: "vpt_deep"             # dynamic / vpt_deep
    INIT_SOURCE: "learned"    # learned / distributor_mean
    DEEP: True
    NUM_TOKENS: 32
    DROPOUT: 0.0
    DISTRIBUTOR:
      ENABLE: True
      DISABLE_SAMPLING: True

  SEMANTIC_BRANCH:
    ENABLE: True

  AFFINITY:
    ENABLE: True

  R_SIMILARITY:
    ENABLE: True
    USE_COSINE: True
    LOGIT_SCALE_INIT: 10.0

  CONSISTENCY:
    ENABLE: False
    PROJ: "linear"
    DIST: "cosine"

SOLVER:
  BASE_LR: 0.0006
  WEIGHT_DECAY: 0.00001
  WARMUP_EPOCH: 3
  TOTAL_EPOCH: 30
  LOSS: "vspcn_baseline"     # softmax_cm   vspcn_baseline
  LOSS_VSPCN_AR_WEIGHT: 0.0005
  LOSS_CM_WEIGHT: 0.05
  LOSS_CONS_WEIGHT: 0.00
  LOSS_ANCHOR_CONS_WEIGHT: 0.00
  LOSS_FREE_KD_WEIGHT: 0.0
  OPTIMIZER: "adamw"
  SCHEDULER: "cosine"
  BIAS_MULTIPLIER: 1.0
  VIS:
    ENABLE: True
    FINAL_ONLY: True
    EPOCH_LIST: []
    SPLITS: ["test_unseen"]
    MAX_SAMPLES: 5
    CORRECT_SAMPLES: 3
    WRONG_SAMPLES: 2
    ROLLOUT: True
