#!/usr/bin/env python3

"""Config system (based on Detectron's)."""

from .config_node import CfgNode

_C = CfgNode()
# ==========================================================
# A. 全局运行配置
# ==========================================================
_C.OUTPUT_DIR = "./output"
_C.RUN_N_TIMES = 5
_C.CUDNN_BENCHMARK = False
_C.NUM_GPUS = 1
_C.NUM_SHARDS = 1
_C.SEED = None

# ==========================================================
# B. MODEL：模型主配置
# ==========================================================
_C.MODEL = CfgNode()
_C.MODEL.WEIGHT_PATH = ""
_C.MODEL.MODEL_ROOT = "weights/official"
_C.MODEL.TYPE = "vit"
_C.MODEL.CLASSIFIER = "r_similarity"        # r_similarity vspcn_baseline

_C.MODEL.PROMPT = CfgNode()
_C.MODEL.PROMPT.ENABLE = True
_C.MODEL.PROMPT.NUM_TOKENS = 50
_C.MODEL.PROMPT.DEEP = True
_C.MODEL.PROMPT.DROPOUT = 0.0
_C.MODEL.PROMPT.DEBUG_SHAPES = False
_C.MODEL.PROMPT.EVOLVE_INIT_MODE = "identity"
_C.MODEL.LOG_TRAINABLE = True

_C.MODEL.PROMPT.DISTRIBUTOR = CfgNode()
_C.MODEL.PROMPT.DISTRIBUTOR.ENABLE = True
_C.MODEL.PROMPT.DISTRIBUTOR.LATENT_DIM = 256
_C.MODEL.PROMPT.DISTRIBUTOR.HIDDEN_DIM = 512
_C.MODEL.PROMPT.DISTRIBUTOR.POOL = "gap"

_C.MODEL.R_SIMILARITY = CfgNode()
_C.MODEL.R_SIMILARITY.ENABLE = True
_C.MODEL.R_SIMILARITY.PROJ_DIM = -1             # v/s投影到新维度
_C.MODEL.R_SIMILARITY.VISUAL_PROJ_ENABLE = True
_C.MODEL.R_SIMILARITY.USE_COSINE = True
_C.MODEL.R_SIMILARITY.LOGIT_SCALE_INIT = 10.0
_C.MODEL.R_SIMILARITY.FIXED_LOGIT_SCALE = 0.0

_C.MODEL.ROLE_MIGRATION = CfgNode()
_C.MODEL.ROLE_MIGRATION.ENABLE = True
_C.MODEL.ROLE_MIGRATION.EARLY_END = 3
_C.MODEL.ROLE_MIGRATION.LATE_START = 9

_C.MODEL.SEMANTIC_BRANCH = CfgNode()
_C.MODEL.SEMANTIC_BRANCH.ENABLE = True
_C.MODEL.SEMANTIC_BRANCH.NUM_TOKENS = 4
_C.MODEL.SEMANTIC_BRANCH.USE_ANCHOR_FREE = False
_C.MODEL.SEMANTIC_BRANCH.ANCHOR_TOKENS = 8
_C.MODEL.SEMANTIC_BRANCH.FREE_TOKENS = 2
_C.MODEL.SEMANTIC_BRANCH.FREE_COMPETE_LAMBDA = 0.5

_C.MODEL.SEMANTIC_BRANCH.GAMMA_ANCHOR_SCALE = 1.0
_C.MODEL.SEMANTIC_BRANCH.GAMMA_FREE_SCALE = 1.0
_C.MODEL.SEMANTIC_BRANCH.START_LAYER = 0
_C.MODEL.SEMANTIC_BRANCH.END_LAYER = -1
_C.MODEL.SEMANTIC_BRANCH.GAMMA_MIN = 0.05
_C.MODEL.SEMANTIC_BRANCH.GAMMA_MAX = 1.0

_C.MODEL.SEMANTIC_BRANCH.CROSS_ATTN_ENABLE = True
_C.MODEL.SEMANTIC_BRANCH.CROSS_ATTN_HEADS = 4
_C.MODEL.SEMANTIC_BRANCH.CROSS_ATTN_DROPOUT = 0.0
_C.MODEL.SEMANTIC_BRANCH.CROSS_ATTN_PRE_NORM = True
_C.MODEL.SEMANTIC_BRANCH.CROSS_ATTN_USE_FFN = True

_C.MODEL.SEMANTIC_BRANCH.DELTA_GATE_SP = 0.0
_C.MODEL.SEMANTIC_BRANCH.DELTA_GATE_SV = 1.0
_C.MODEL.SEMANTIC_BRANCH.DELTA_GATE_PS = 0.0
_C.MODEL.SEMANTIC_BRANCH.DELTA_GATE_VS = 0.0
_C.MODEL.SEMANTIC_BRANCH.CROSS_ATTN_COMPUTE_ALL_ROUTES = False
_C.MODEL.SEMANTIC_BRANCH.DELTA_GATE_OPEN_ROUTES = ["sv-att"]
_C.MODEL.SEMANTIC_BRANCH.DELTA_GATE_THRESHOLD = 0.0
_C.MODEL.SEMANTIC_BRANCH.DELTA_GATE_NORMALIZE = True

_C.MODEL.CONSISTENCY = CfgNode()
_C.MODEL.CONSISTENCY.ENABLE = False
_C.MODEL.CONSISTENCY.PROJ = "linear"
_C.MODEL.CONSISTENCY.DIST = "cosine"

_C.MODEL.AFFINITY = CfgNode()
_C.MODEL.AFFINITY.ENABLE = False
_C.MODEL.AFFINITY.RETURN_CROSS = True
_C.MODEL.AFFINITY.NORMALIZE = True
_C.MODEL.AFFINITY.DETACH = True
_C.MODEL.AFFINITY.VIS = True

_C.MODEL.ADAPTER = CfgNode()
_C.MODEL.ADAPTER.REDUCATION_FACTOR = 8
_C.MODEL.ADAPTER.STYLE = "Pfeiffer"

_C.SOLVER = CfgNode()
_C.SOLVER.LOSS = "softmax_margin_cm"
_C.SOLVER.LOSS_MARGIN = 0.05
_C.SOLVER.LOSS_CM_WEIGHT = 0.5
_C.SOLVER.LOSS_VSPCN_AR_WEIGHT = 0.02
_C.SOLVER.LOSS_HN_MARGIN_ENABLE = False
_C.SOLVER.LOSS_HN_MARGIN_WEIGHT = 0.05
_C.SOLVER.LOSS_HN_MARGIN_VALUE = 0.1
_C.SOLVER.LOSS_HN_MARGIN_START_EPOCH = 0
_C.SOLVER.LOSS_HN_DETACH_NEG = True
_C.SOLVER.LOSS_ROLE_EARLY_WEIGHT = 0.0
_C.SOLVER.LOSS_ROLE_LATE_WEIGHT = 0.0
_C.SOLVER.LOSS_AGR_RES_WEIGHT = 0.0
_C.SOLVER.LOSS_AVS_ENT_WEIGHT = 0.0
_C.SOLVER.LOSS_CONS_WEIGHT = 0.0
_C.SOLVER.LOSS_ANCHOR_CONS_WEIGHT = 0.0
_C.SOLVER.LOSS_FREE_KD_WEIGHT = 0.0

_C.SOLVER.DIAG = CfgNode()
_C.SOLVER.DIAG.SHUFFLE_RAW_TARGETS = False
_C.SOLVER.DIAG.SHUFFLE_PROTOTYPES = False
_C.SOLVER.DIAG.STRICT_CHECKS = False
_C.SOLVER.DIAG.PRINT_LOSS_WIRING = False
_C.SOLVER.OPTIMIZER = "adamw"
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.WEIGHT_DECAY = 0.0001
_C.SOLVER.WEIGHT_DECAY_BIAS = 0
_C.SOLVER.ADAM_BETA1 = 0.9
_C.SOLVER.ADAM_BETA2 = 0.999
_C.SOLVER.ADAM_EPS = 1e-8
_C.SOLVER.PATIENCE = 300
_C.SOLVER.SCHEDULER = "cosine"          # 学习率随 epoch 怎么变化
_C.SOLVER.BASE_LR = 0.0005
_C.SOLVER.BIAS_MULTIPLIER = 1.
_C.SOLVER.WARMUP_EPOCH = 5
_C.SOLVER.TOTAL_EPOCH = 30
_C.SOLVER.LOG_EVERY_N = 1000
_C.SOLVER.DEBUG_GRAD_NORM = False
_C.SOLVER.DEBUG_TRACE_ONCE = False
_C.SOLVER.DEBUG_SHAPES = False
_C.SOLVER.EVAL_MODE = "zsl"

_C.SOLVER.MONITOR = CfgNode()
_C.SOLVER.MONITOR.ENABLE = False
_C.SOLVER.MONITOR.EVERY_EPOCH = 1
_C.SOLVER.MONITOR.MAX_SAMPLES = 512
_C.SOLVER.MONITOR.SAVE_JSON = True
_C.SOLVER.MONITOR.SAVE_CSV = True
_C.SOLVER.MONITOR.SAVE_HEATMAP = False
_C.SOLVER.MONITOR.HEATMAP_TOPK = 50
_C.SOLVER.MONITOR.TOKEN_PATCH_STATS_ENABLE = True
_C.SOLVER.MONITOR.TOKEN_PATCH_SOURCE = "asv"
_C.SOLVER.MONITOR.TOKEN_PATCH_HEAD_MODE = "head_avg"
_C.SOLVER.MONITOR.TOKEN_PATCH_TOPRHO = 0.2
_C.SOLVER.MONITOR.TOKEN_PATCH_SAVE_MAPS = False
_C.SOLVER.MONITOR.TOKEN_PATCH_MAX_SAMPLES = 8
_C.SOLVER.MONITOR.AFFINITY_SUMMARY_ENABLE = True
_C.SOLVER.MONITOR.AFFINITY_SAVE_RAW_DUMP = False
_C.SOLVER.MONITOR.AFFINITY_KEYNODE_VIZ_ENABLE = True
_C.SOLVER.MONITOR.AFFINITY_KEYNODE_SPLITS = ["test_seen", "test_unseen"]
_C.SOLVER.MONITOR.AFFINITY_KEYNODE_MAX_FIGS = 1
_C.SOLVER.MONITOR.AFFINITY_KEYNODE_LAYER_POLICY = "first_middle_last"

_C.SOLVER.VIS = CfgNode()
_C.SOLVER.VIS.ENABLE = False
_C.SOLVER.VIS.EVERY_EPOCH = 1
_C.SOLVER.VIS.EPOCH_LIST = []
_C.SOLVER.VIS.SPLITS = ["test_unseen"]
_C.SOLVER.VIS.MAX_SAMPLES = 8
_C.SOLVER.VIS.SAVE_RAW = True
_C.SOLVER.VIS.SAVE_IMAGES = True
_C.SOLVER.VIS.LOCAL_CONTROL = True
_C.SOLVER.VIS.ROLLOUT = True
_C.SOLVER.VIS.GT_HN_COMPARE = True
_C.SOLVER.VIS.TRENDS = True
_C.SOLVER.DBG_TRAINABLE = False

_C.DATA = CfgNode()
_C.DATA_ROOT = ""
_C.DATA.NAME = "CUB"
_C.DATA.DATAPATH = "datasets/CUB/CUB_200_2011"
_C.DATA.FEATURE = "sup_vitb16_224"
_C.DATA.NUMBER_CLASSES = 200
_C.DATA.CLASS_WEIGHTS_TYPE = "none"
_C.DATA.CROPSIZE = 224
_C.DATA.BATCH_SIZE = 32
_C.DATA.NUM_WORKERS = 4
_C.DATA.PIN_MEMORY = True

_C.DATA.XLSA = CfgNode()
_C.DATA.XLSA.ENABLED = True
_C.DATA.XLSA.RES101_PATH = "datasets/xlsa17/xlsa17/data/CUB/res101.mat"
_C.DATA.XLSA.SPLIT_PATH = "datasets/xlsa17/xlsa17/data/CUB/att_splits.mat"
_C.DATA.XLSA.PROTOCOL_MODE = "dev"     #dev / final_zsl / final_gzsl
_C.DIST_BACKEND = "gloo"
_C.DIST_INIT_PATH = "env://"
_C.DIST_INIT_FILE = ""


def get_cfg():
    """Get a copy of the default config."""
    return _C.clone()
