#!/usr/bin/env python3

"""Config system (based on Detectron's)."""

from .config_node import CfgNode

_C = CfgNode()
# ==========================================================
# A. 全局运行配置
# ==========================================================
_C.OUTPUT_DIR = "./output"
_C.RUN_N_TIMES = 5
_C.CUDNN_BENCHMARK = False
_C.NUM_GPUS = 1
_C.NUM_SHARDS = 1
_C.SEED = None
_C.DIST_RANK = 0

# ==========================================================
# B. MODEL：模型主配置
# ==========================================================
_C.MODEL = CfgNode()
_C.MODEL.WEIGHT_PATH = ""
_C.MODEL.MODEL_ROOT = "weights/official"
_C.MODEL.TYPE = "vit"
_C.MODEL.CLASSIFIER = "r_similarity"

_C.MODEL.PROMPT = CfgNode()
_C.MODEL.PROMPT.ENABLE = True
_C.MODEL.PROMPT.BACKEND = "dynamic"   # dynamic / vpt_deep
_C.MODEL.PROMPT.INIT_SOURCE = "learned"   # learned / distributor_mean
_C.MODEL.PROMPT.NUM_TOKENS = 50
_C.MODEL.PROMPT.DEEP = False
_C.MODEL.PROMPT.DROPOUT = 0.0
_C.MODEL.PROMPT.DEBUG_SHAPES = False
_C.MODEL.LOG_TRAINABLE = True

_C.MODEL.PROMPT.DISTRIBUTOR = CfgNode()
_C.MODEL.PROMPT.DISTRIBUTOR.ENABLE = True                  # 是否启用 prompt_init_provider；通常配合 INIT_SOURCE="distributor_mean" 使用
_C.MODEL.PROMPT.DISTRIBUTOR.SOURCE = "token_mlp"           # 视觉统计来源：token_mlp / vit_cls_prepass / cnn_torchvision / clip_frozen / dinov2_small；vit_cls_prepass_constant仅用于非条件对照
_C.MODEL.PROMPT.DISTRIBUTOR.STATS_HIDDEN_DIM = 64          # stats head 中间维度 H：视觉输入先降到 H，再输出 mu/logvar
_C.MODEL.PROMPT.DISTRIBUTOR.INSTANCE_TOKENS = 25           # 图像条件 instance prompt 数量；与 DOMAIN_TOKENS 之和必须等于 NUM_TOKENS
_C.MODEL.PROMPT.DISTRIBUTOR.DOMAIN_TOKENS = 25             # 任务/数据集级 learnable domain prompt 数量
_C.MODEL.PROMPT.DISTRIBUTOR.OUTPUT_PARAM = "logvar"        # 分布参数输出形式；当前只支持 logvar，即 stats_out=[mu, logvar]
_C.MODEL.PROMPT.DISTRIBUTOR.LOGVAR_MIN = -10.0             # logvar clamp 下界，防止 std 过小导致数值异常
_C.MODEL.PROMPT.DISTRIBUTOR.LOGVAR_MAX = 5.0               # logvar clamp 上界，防止 std 爆炸
_C.MODEL.PROMPT.DISTRIBUTOR.EVAL_SAMPLE_MODE = "fixed_eps"      # 评测采样：mean 使用 eps=0；fixed_eps 使用固定噪声 buffer
_C.MODEL.PROMPT.DISTRIBUTOR.FIXED_EPS_SEED = 0             # fixed_eps buffer 的独立随机种子；不影响全局 torch 随机状态
_C.MODEL.PROMPT.DISTRIBUTOR.USE_SLOT_EMBED = True         # 是否给每个 instance prompt 加可学习槽位编码

_C.MODEL.PROMPT.DISTRIBUTOR.CNN_NAME = "efficientnet_b0"   # cnn_torchvision 候选：efficientnet_b0 / mobilenet_v3_small
_C.MODEL.PROMPT.DISTRIBUTOR.CLIP_NAME = "mobileclip_s0"    # clip_frozen 候选：mobileclip_s0 / tinyclip_vit8m；需本地权重
_C.MODEL.PROMPT.DISTRIBUTOR.CLIP_LOCAL_DIR = ""            # clip_frozen 本地权重目录，期望存在 {CLIP_NAME}.pt
_C.MODEL.PROMPT.DISTRIBUTOR.DINO_LOCAL_DIR = ""            # dinov2_small 本地权重目录，期望存在 dinov2_small.pt
_C.MODEL.PROMPT.DISTRIBUTOR.EXTERNAL_ALLOW_DOWNLOAD = False # 是否允许 torchvision 自动下载 CNN 权重；默认禁止
_C.MODEL.PROMPT.DISTRIBUTOR.DEBUG_DISTRIBUTOR_SHAPES = False # 打印一次 distributor 输入、mu/logvar、prompt 形状
_C.MODEL.PROMPT.DISTRIBUTOR.DEEP_RESIDUAL = CfgNode()
_C.MODEL.PROMPT.DISTRIBUTOR.DEEP_RESIDUAL.ENABLE = False
_C.MODEL.PROMPT.DISTRIBUTOR.DEEP_RESIDUAL.ARCHITECTURE_ID = "B1-direct-mean-residual"
_C.MODEL.PROMPT.DISTRIBUTOR.DEEP_RESIDUAL.GATE_INIT = 0.0

_C.MODEL.R_SIMILARITY = CfgNode()
_C.MODEL.R_SIMILARITY.SCORE_MODE = "dot"          # dot / cosine
_C.MODEL.R_SIMILARITY.LEARNABLE_SCALE = False
_C.MODEL.R_SIMILARITY.LOGIT_SCALE_INIT = 10.0
_C.MODEL.R_SIMILARITY.FIXED_LOGIT_SCALE = 0.0

_C.MODEL.SEMANTIC_TOKENS = CfgNode()
_C.MODEL.SEMANTIC_TOKENS.ENABLE = True
_C.MODEL.SEMANTIC_TOKENS.TOKENIZER = "linear"      # linear / orthogonal
_C.MODEL.SEMANTIC_TOKENS.NUM_TOKENS = 1
_C.MODEL.SEMANTIC_TOKENS.INPUT_DIM = 312
_C.MODEL.SEMANTIC_TOKENS.TRAIN_SOURCE = "label"       # label / class_mean / none / random_fixed / label_shuffle / learned_token
_C.MODEL.SEMANTIC_TOKENS.EVAL_SOURCE = "none"         # label / class_mean / none / random_fixed / label_shuffle / learned_token
# BEGIN SEMANTIC_ABLATION_EXPERIMENT                    # 语义替换实验+att mass统计  ΔAsv
_C.MODEL.SEMANTIC_TOKENS.RANDOM_SEED = 0
_C.MODEL.SEMANTIC_TOKENS.RANDOM_STD = 1.0
_C.MODEL.SEMANTIC_TOKENS.LEARNED_INIT_STD = 0.02
# END SEMANTIC_ABLATION_EXPERIMENT
_C.MODEL.SEMANTIC_TOKENS.BLOCK_S_TO_CLS = False
_C.MODEL.SEMANTIC_TOKENS.ORTHO = CfgNode()
_C.MODEL.SEMANTIC_TOKENS.ORTHO.GROUP_MODE = "manual_cub8"  # manual_cub8 / equal / prefix
_C.MODEL.SEMANTIC_TOKENS.ORTHO.TEXT_MODE = "none"          # none / null_residual / text_init_codebook

_C.MODEL.SEMANTIC_TOKENS.ORTHO.ATTRIBUTES_PATH = "datasets/CUB/attributes.txt"
_C.MODEL.SEMANTIC_TOKENS.ORTHO.TEXT_EMBED_PATH = "datasets/xlsa17/xlsa17/data/CUB/cub_attributes_sbert_all_mpnet_base_v2.pt"
_C.MODEL.SEMANTIC_TOKENS.ORTHO.TEXT_GATE_INIT = 0.0
_C.MODEL.SEMANTIC_TOKENS.ORTHO.CODEBOOK_TRAINABLE = False   # 让 semantic token 更像确定的属性编码，而不是又变成一组自由可学习 prompt
_C.MODEL.SEMANTIC_TOKENS.ORTHO.CODEBOOK_SEED = 0
_C.MODEL.SEMANTIC_TOKENS.ORTHO.DEBUG = False

_C.MODEL.GRAPH_INPUT = CfgNode()
_C.MODEL.GRAPH_INPUT.NUM_CLASSES = 200               # CUB 全局类别数；类别关系图 G 的尺寸为 [NUM_CLASSES, NUM_CLASSES]
_C.MODEL.GRAPH_INPUT.ATTR_DIM = 312                  # CUB 属性维度
_C.MODEL.GRAPH_INPUT.TEXT_DIM = 768                  # prompt posterior 与 Graph-GP prototype 的 latent 维度
_C.MODEL.GRAPH_INPUT.GRAPH_SOURCE = "method1_diff"   # Graph-GP external graph key：method1_diff / method2_diff / method3_diff
_C.MODEL.GRAPH_INPUT.EXTERNAL_GRAPH_PATH = ""        # GRAPH_SOURCE 指向外部 key 时读取的 [C,C] 类别关系矩阵文件；支持 .npz/.npy/.pt/.pth
_C.MODEL.GRAPH_INPUT.EXTERNAL_GRAPH_SYMMETRIZE = True # 是否强制 external graph 对称化
_C.MODEL.GRAPH_INPUT.EXTERNAL_GRAPH_CLAMP = True     # 是否把 external graph 截断到 [0,1]
_C.MODEL.GRAPH_INPUT.EXTERNAL_GRAPH_DIAG_VALUE = 1.0 # external graph 对角线值；负数表示不改对角线
_C.MODEL.GRAPH_INPUT.EPS = 1e-8                      # GraphProbPrior 概率归一化与 log 的数值稳定下界

_C.MODEL.GRAPH_PROB_PRIOR = CfgNode()
_C.MODEL.GRAPH_PROB_PRIOR.ENABLE = False               # GraphProbPrior 启用后固定使用 Graph-GP energy classification
_C.MODEL.GRAPH_PROB_PRIOR.LOSS_WEIGHT = 0.0             # Graph-GP 辅助损失权重
_C.MODEL.GRAPH_PROB_PRIOR.PRIOR_LOGVAR_CONST = 0.0      # GRAPH_GP_PRIOR_VAR_SOURCE=constant 时使用的固定 logvar
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_SUPPORT_RATIO = 0.8  # graph_gp_conditioned 中 seen 类划为 support-seen 的比例；剩余 seen 类作为 pseudo-unseen 诊断外推能力
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_SPLIT_EVERY_EPOCH = 1 # 每多少个 epoch 重新划分一次 support-seen / pseudo-unseen；1 表示每个 epoch 换一次
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_SPLIT_SEED = 2027    # Graph-GP 类别 split 的随机种子；保证 support/pseudo 划分可复现
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_CENTER_SOURCE = "posterior_mu" # Graph-GP 视觉中心来源；第一版只支持 posterior_mu，保证和 KL 对齐空间一致
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_DETACH_CENTERS = True # 统计 V_support 时截断 posterior_mu 梯度，避免 prior target 和 posterior 相互追逐
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_OBS_NOISE_MODE = "class_var_over_count" # R_s 观测噪声：constant / class_var_over_count
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_OBS_NOISE_CONST = 0.05 # constant 模式下每个 support center 的观测噪声标量
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_OBS_NOISE_MIN = 1e-4 # R_s 下界；防止 K_ss + R_s 对角线过小导致 solve 不稳定
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_OBS_NOISE_MAX = 1.0  # R_s 上界；防止某些类被过大噪声完全忽略
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_RIDGE = 1e-4         # 加到 K_ss + R_s 对角线上的数值稳定项；只服务线性方程求解
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_KERNEL_SYMMETRIZE = True # 条件推断前是否对 graph kernel 做对称化
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_KERNEL_CLAMP = True  # 条件推断前是否把 graph kernel 裁到非负，避免负边直接进入协方差
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_KERNEL_NORMALIZE = "diag" # Graph-GP kernel 归一化：diag 让对角线尺度接近 1；none 保留原始尺度
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_PRIOR_VAR_SOURCE = "unit" # Graph-GP prior_logvar 来源：unit / constant / dynamic_uncertainty
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_PRIOR_VAR_FLOOR = 0.05    # dynamic_uncertainty 的最低 prior variance，避免 KL 因 prior 太窄而爆炸
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_PRIOR_VAR_PROTO_WEIGHT = 1.0  # dynamic_uncertainty 中 GP predictive uncertainty 的权重
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_PRIOR_VAR_VISUAL_WEIGHT = 1.0 # dynamic_uncertainty 中传播后的类内视觉方差权重
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_PRIOR_VAR_MIN = 1e-4      # dynamic_uncertainty 最终 prior variance 下界
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_PRIOR_VAR_MAX = 10.0      # dynamic_uncertainty 最终 prior variance 上界
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_USE_PSEUDO_UNSEEN = True # 训练期是否在 seen 类内部划 pseudo-unseen，用来模拟 ZSL 外推
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_MATCH_DETACH_PRIOR = True # posterior 对齐 M_star 时是否 detach；第一版应保持 True
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_OBJECTIVE = "energy_classification" # Graph-GP 自身训练目标；当前只支持 energy_classification
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_ENERGY_TAU = 1.0          # Graph-GP Energy Classification 的 softmax 温度
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_ENERGY_CLASS_SPACE = "seen" # energy classification 的类别空间；当前只支持 seen
_C.MODEL.GRAPH_PROB_PRIOR.GRAPH_GP_PSEUDO_WEIGHT = 1.0       # pseudo-unseen 样本在 energy CE 中的样本权重；1 表示不额外加权
_C.MODEL.GRAPH_PROB_PRIOR.MONITOR_ENABLE = False        # 是否记录 Graph-GP kernel、prototype、energy 与 GZSL 风险监测量
_C.MODEL.GRAPH_PROB_PRIOR.MONITOR_TOPK = 5              # 监测 top-k mass 时使用的 k
_C.MODEL.GRAPH_PROB_PRIOR.MONITOR_EVERY_N = 37           # 每多少次实际 GraphProbPrior 训练 forward 记录一次监测量；1 表示每次都记录
_C.MODEL.GRAPH_PROB_PRIOR.MONITOR_EFFECTIVE_RANK = False # 是否计算 effective-rank 监测；关闭可避免 SVD/MAGMA 日志
_C.MODEL.GRAPH_PROB_PRIOR.DEBUG = False                 # 打印一次 GraphProbPrior 的关键 shape 和 loss 标量

_C.MODEL.AFFINITY = CfgNode()
_C.MODEL.AFFINITY.ENABLE = False
_C.MODEL.AFFINITY.DETACH = True
_C.MODEL.AFFINITY.VIS = True

_C.MODEL.ATTENTION_MEDIATION = CfgNode()
# ATTENTION_MEDIATION 是新增的 block 内 mediated attention correction 分支。
# 默认关闭；开启时会在每层 ViT self-attention 内部额外构造 mediated route，
# 只对 prompt/semantic token 产生 correction，不替换原始 ViT attention 主路径。
# SOURCE:
#   probs  - 从 full softmax 后的真实 attention 概率子块构造 route。
#   scores - 从 softmax 前 QK logits 子块构造局部条件 route，再用 log-ratio bias 回到 full softmax。
# EXECUTION_MODE:
#   attention_parallel 表示只复制 attention 级别计算，不复制完整 Transformer block。
# MLP_POLICY:
#   enter_mlp 表示 correction 在当前层 MLP 前合并；skip_mlp 表示 block 后只写回 P/S residual。
# ROUTE_SCOPE/MASS_MODE:
#   visual_block 只改 P->V/S->V 的 visual 子块；full_row 直接构造完整 attention row。
#   row_preserve 保持每个 P/S token 的 visual mass；block_redistribute 允许组内重分配 visual mass。
# PROMPT_ROUTE/SEMANTIC_ROUTE:
#   分别控制 prompt-mediated 和 semantic-mediated 路径的方向。
# *_GAMMA_INIT:
#   每层可学习 gate 的初始值；0 表示初始等价于不开启 correction。
_C.MODEL.ATTENTION_MEDIATION.ENABLE = False
_C.MODEL.ATTENTION_MEDIATION.SOURCE = "probs"             # probs / scores；从 full attention 概率或 logits 构造 mediated route
_C.MODEL.ATTENTION_MEDIATION.EXECUTION_MODE = "attention_parallel"  # attention_parallel / block_parallel
_C.MODEL.ATTENTION_MEDIATION.MLP_POLICY = "enter_mlp"     # enter_mlp / skip_mlp
_C.MODEL.ATTENTION_MEDIATION.ROUTE_SCOPE = "visual_block" # visual_block / full_row
_C.MODEL.ATTENTION_MEDIATION.PROMPT_ROUTE = "S_to_P_and_V"    # S_to_P_and_V / P_to_S_to_V
_C.MODEL.ATTENTION_MEDIATION.SEMANTIC_ROUTE = "S_to_P_to_V"   # S_to_P_to_V / P_to_S_and_V
_C.MODEL.ATTENTION_MEDIATION.MASS_MODE = "row_preserve"   # row_preserve / block_redistribute
_C.MODEL.ATTENTION_MEDIATION.BETA_PROMPT_MASS = 0.0
_C.MODEL.ATTENTION_MEDIATION.BETA_SEMANTIC_MASS = 0.0
_C.MODEL.ATTENTION_MEDIATION.PROMPT_GAMMA_INIT = 0.0
_C.MODEL.ATTENTION_MEDIATION.SEMANTIC_GAMMA_INIT = 0.0
# 约束：
#   block_parallel 必须配合 MLP_POLICY="enter_mlp"。
#   full_row 已经构造完整 attention row，因此不能配合 block_redistribute。

_C.MONITOR = CfgNode()
_C.MONITOR.ENABLE = True
_C.MONITOR.WRITE_EPOCH_CSV = True
_C.MONITOR.WRITE_STEP_JSONL = True
_C.MONITOR.WRITE_EVENTS_JSONL = True
_C.MONITOR.OUTPUT_POLICY = "error_if_exists"  # error_if_exists / resume / overwrite；仅约束监测产物，避免同一 run 混写
_C.MONITOR.STEP_EVERY_N = 100  # train/debug/prompt/AM/affinity 的全局步采样周期；GraphProbPrior 使用自身周期
_C.MONITOR.PROMPT = CfgNode()
_C.MONITOR.PROMPT.ENABLE = True  # distributor_mean 或 deterministic deep residual 数据源启用时输出
_C.MONITOR.ATTENTION_MEDIATION = CfgNode()
_C.MONITOR.ATTENTION_MEDIATION.ENABLE = True  # 仅模型 Attention Mediation 分支实际启用时才会输出
_C.MONITOR.AFFINITY = CfgNode()
_C.MONITOR.AFFINITY.ENABLE = False  # 开启后会要求 forward_with_affinity，存在额外显存和计算开销
_C.MONITOR.NUMERICAL_GUARD = CfgNode()
_C.MONITOR.NUMERICAL_GUARD.ENABLE = True
_C.MONITOR.OPTIMIZER_SANITY = CfgNode()
_C.MONITOR.OPTIMIZER_SANITY.ENABLE = True
_C.MONITOR.PREDICTION_HEALTH = CfgNode()
_C.MONITOR.PREDICTION_HEALTH.ENABLE = True
_C.MONITOR.CLASS_ERROR = CfgNode()
_C.MONITOR.CLASS_ERROR.ENABLE = True
_C.MONITOR.CLASS_ERROR.TOP_CONFUSIONS = 10
_C.MONITOR.CALIBRATION = CfgNode()
_C.MONITOR.CALIBRATION.ENABLE = True
_C.MONITOR.CALIBRATION.GAMMA_GRID = [
    -3.0, -2.5, -2.0, -1.5, -1.0, -0.75, -0.5, -0.25,
    0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0,
]
_C.MONITOR.CALIBRATION.SEEN_CLASS_IDS = []
_C.MONITOR.TRAIN_EVAL = CfgNode()
_C.MONITOR.TRAIN_EVAL.ENABLE = False
_C.MONITOR.TRAIN_EVAL.EVERY_N = 1
_C.MONITOR.LOSS_COMPONENT_TRAJECTORY = CfgNode()
_C.MONITOR.LOSS_COMPONENT_TRAJECTORY.ENABLE = True
_C.MONITOR.PREDICTION_TRANSITION_TRAJECTORY = CfgNode()
_C.MONITOR.PREDICTION_TRANSITION_TRAJECTORY.ENABLE = False
_C.MONITOR.PREDICTION_TRANSITION_TRAJECTORY.SPLITS = ["test_seen", "test_unseen"]
_C.MONITOR.MILESTONE_PROBE = CfgNode()
_C.MONITOR.MILESTONE_PROBE.ENABLE = False
_C.MONITOR.MILESTONE_PROBE.INCLUDE_WARMUP_END = True
_C.MONITOR.MILESTONE_PROBE.FRACTIONS = [0.4, 0.7]
_C.MONITOR.MILESTONE_PROBE.SAVE_CHECKPOINTS = True
_C.MONITOR.MILESTONE_PROBE.RUN_FIXED_PROBE = True
_C.MONITOR.MILESTONE_PROBE.PROFILE = "milestone_core"
# Standalone checkpoint-only replay: explicit CLI invocation is the request
# gate.  The three components and full-test requirement are algorithmic
# invariants rather than user-relaxable configuration.
_C.MONITOR.DECISION_GAIN_DECOMPOSITION = CfgNode()
_C.MONITOR.DECISION_GAIN_DECOMPOSITION.GLOBAL_SCALE_FACTORS = [0.5, 2.0, 4.0]
_C.MONITOR.DECISION_GAIN_DECOMPOSITION.FACTORIZATION_EPS = 1.0e-8
_C.MONITOR.DECISION_GAIN_DECOMPOSITION.RECONSTRUCTION_ATOL = 1.0e-5
_C.MONITOR.DECISION_GAIN_DECOMPOSITION.BATCH_SIZE = 128
# Standalone method-level checkpoint replay.  It is intentionally not an
# every-epoch monitor because it needs both complete final_gzsl test splits.
_C.MONITOR.LOGIT_GEOMETRY = CfgNode()
_C.MONITOR.LOGIT_GEOMETRY.FACTORIZATION_EPS = 1.0e-8
_C.MONITOR.LOGIT_GEOMETRY.RECONSTRUCTION_ATOL = 1.0e-5
_C.MONITOR.LOGIT_GEOMETRY.BATCH_SIZE = 128
_C.MONITOR.DIAGNOSTICS = CfgNode()
_C.MONITOR.DIAGNOSTICS.ENABLE = True
_C.MONITOR.SEMANTIC_GRAPH_REFERENCE = CfgNode()
_C.MONITOR.SEMANTIC_GRAPH_REFERENCE.ENABLE = True
_C.MONITOR.SEMANTIC_GRAPH_REFERENCE.EDGE_THRESHOLD = 0.5
_C.MONITOR.SEMANTIC_GRAPH_REFERENCE.NEIGHBOR_K = 5
_C.MONITOR.SEMANTIC_GRAPH_REFERENCE.TEMPERATURE = 1.0
_C.MONITOR.PROMPT_PARAMETER = CfgNode()
_C.MONITOR.PROMPT_PARAMETER.ENABLE = True
_C.MONITOR.SEMANTIC_TOKEN = CfgNode()
_C.MONITOR.SEMANTIC_TOKEN.ENABLE = True
_C.MONITOR.AUXILIARY_LOSS = CfgNode()
_C.MONITOR.AUXILIARY_LOSS.ENABLE = True
_C.MONITOR.PROBE = CfgNode()
_C.MONITOR.PROBE.ENABLE = False
_C.MONITOR.PROBE.EXECUTION_PROFILE = "final_full"
_C.MONITOR.PROBE.SELECTION_SEED = 424242
_C.MONITOR.PROBE.ROBUSTNESS_SELECTION_SEEDS = []
_C.MONITOR.PROBE.PER_CLASS = 2
_C.MONITOR.PROBE.MAX_SAMPLES = 384
_C.MONITOR.PROBE.BATCH_SIZE = 32
_C.MONITOR.PROBE.NUM_WORKERS = 0
_C.MONITOR.PROBE.PIN_MEMORY = False
_C.MONITOR.PROBE.FINAL_ONLY = True
_C.MONITOR.PROBE.REQUIRE_FULL_CLASS_COVERAGE = True
_C.MONITOR.PROBE.REQUIRE_PER_CLASS_QUOTA = True
_C.MONITOR.PROBE.ALLOW_MAX_SAMPLES_TRUNCATION = False
_C.MONITOR.PROBE.LAYERS = [0, 3, 6, 9, 11]
_C.MONITOR.PROBE.ATTENTION_ENABLE = True
_C.MONITOR.PROBE.AFFINITY_ENABLE = True
_C.MONITOR.PROBE.AFFINITY_TEMPERATURE = 1.0
_C.MONITOR.PROBE.AFFINITY_SATURATION_THRESHOLD = 10.0
_C.MONITOR.PROBE.ATTRIBUTE_CONCEPT_ENABLE = False
_C.MONITOR.PROBE.ATTRIBUTE_CONCEPT_PATCH_RATIO = 0.2
_C.MONITOR.PROBE.PATCH_SEMANTIC_TRANSPORT = CfgNode()
_C.MONITOR.PROBE.PATCH_SEMANTIC_TRANSPORT.ENABLE = False
_C.MONITOR.PROBE.PATCH_SEMANTIC_TRANSPORT.COST = "cosine"
_C.MONITOR.PROBE.PATCH_SEMANTIC_TRANSPORT.TEMPERATURE = 1.0
_C.MONITOR.PROBE.PATCH_SEMANTIC_TRANSPORT.PATCH_RATIO = 0.2
_C.MONITOR.PROBE.FORWARD_EQUIVALENCE_ATOL = 1e-5
_C.MONITOR.PROBE.FORWARD_EQUIVALENCE_MARGIN_ATOL = 1e-5
_C.MONITOR.PROBE.TARGET_RELEVANCE = CfgNode()
_C.MONITOR.PROBE.TARGET_RELEVANCE.ENABLE = False
_C.MONITOR.PROBE.TARGET_RELEVANCE.BATCH_SIZE = 4
_C.MONITOR.PROBE.EXPLANATION_VALIDITY = CfgNode()
_C.MONITOR.PROBE.EXPLANATION_VALIDITY.ENABLE = False
_C.MONITOR.PROBE.EXPLANATION_VALIDITY.LAYERS = []
_C.MONITOR.PROBE.EXPLANATION_VALIDITY.K_FRACTIONS = [0.1, 0.3, 0.5]
_C.MONITOR.PROBE.EXPLANATION_VALIDITY.CONDITIONS = ["positive", "negative", "random"]
_C.MONITOR.PROBE.EXPLANATION_VALIDITY.PATHS = [
    "cls_to_prompt",
    "prompt_to_cls",
    "prompt_to_patch",
    "patch_to_prompt",
]
_C.MONITOR.PROBE.EXPLANATION_VALIDITY.RANDOM_SEED = 8675309
_C.MONITOR.PROBE.PROMPT_ANALYSIS = CfgNode()
_C.MONITOR.PROBE.PROMPT_ANALYSIS.ENABLE = False
_C.MONITOR.PROBE.PROMPT_ANALYSIS.CONTENT_ENABLE = True
_C.MONITOR.PROBE.PROMPT_ANALYSIS.SOURCE_DECOMPOSITION_ENABLE = True
_C.MONITOR.PROBE.PROMPT_ANALYSIS.SEMANTIC_GRANULARITY_ENABLE = False
_C.MONITOR.PROBE.PROMPT_ANALYSIS.LOCAL_ATTRIBUTE_INDICES = []
_C.MONITOR.PROBE.PROMPT_ANALYSIS.GLOBAL_ATTRIBUTE_INDICES = []
_C.MONITOR.PROBE.PROMPT_ANALYSIS.FLIP_ENABLE = False
_C.MONITOR.PROBE.PROMPT_ANALYSIS.FLIP_TOPK = 5
_C.MONITOR.PROBE.PROMPT_ANALYSIS.ROLE_PROFILE_EXPORT_ENABLE = False
_C.MONITOR.PROBE.PROMPT_ANALYSIS.LABEL_DEPENDENCY_GUARD_ENABLE = False
_C.MONITOR.PROBE.PROMPT_ANALYSIS.CONTENT_REDUNDANCY_COSINE = 0.9
_C.MONITOR.PROBE.PROMPT_ANALYSIS.CONTENT_OPPOSITION_COSINE = -0.5
_C.MONITOR.PROBE.PROMPT_ANALYSIS.CONTENT_CANCELLATION_RATIO = 0.25
_C.MONITOR.PROBE.PROMPT_ANALYSIS.LOW_USAGE_FRACTION = 0.25
_C.MONITOR.PROBE.PROMPT_ANALYSIS.LOW_FUNCTION_FRACTION = 0.25
_C.MONITOR.PROBE.PROMPT_ANALYSIS.LOW_ROLE_COVERAGE = 0.01
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION = CfgNode()
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.ENABLE = False
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.CANDIDATE_SPACES = [
    "raw_latent",
    "injected_prompt",
    "contextualized_prompt",
    "cls_effect",
    "logit_effect",
]
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.AUXILIARY_VIEWS = [
    "semantic_aligned_contextualized_prompt",
    "decision_margin_effect",
]
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.LAYERS = []
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.PERTURBATION_MODE = "normalized_direction"
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.PERTURBATION_SCALES = [0.01, 0.03]
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.DIRECTION_COUNT = 4
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.RANDOM_SEED = 424243
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.HIERARCHY_TRACE_ENABLE = True
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.HIERARCHY_VARIANT_SOURCE = "controlled_perturbation"
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.HIERARCHY_VARIANT_COUNT = 8
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.HIERARCHY_REFERENCE = "unperturbed_same_checkpoint"
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.BOOTSTRAP_SAMPLES = 200
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.COLLAPSE_RELATIVE_THRESHOLD = 0.05
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.DISTANCE_EPS = 1.0e-8
_C.MONITOR.PROBE.BAYESIAN_OBJECT_SELECTION.EXPORT_SAMPLE_VECTORS = False
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION = CfgNode()
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION.ENABLE = False
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION.PERMUTATION_SEED = 314159
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION.SYNC_LOGIT_ATOL = 1e-5
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION.SYNC_MARGIN_ATOL = 1e-5
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION.MISMATCH_MIN_ACCURACY_DROP = 0.0
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION.MISMATCH_MIN_MARGIN_DROP = 0.0
_C.MONITOR.PROBE.SEMANTIC_INTERVENTION.MISMATCH_MIN_RANK_INCREASE = 0.0
_C.MONITOR.MODULE_EFFECT = CfgNode()
_C.MONITOR.MODULE_EFFECT.ENABLE = False
_C.MONITOR.MODULE_EFFECT.PROMPT_ZERO = True
_C.MONITOR.MODULE_EFFECT.PROMPT_READ_BLOCK = False
_C.MONITOR.MODULE_EFFECT.PROMPT_WRITE_BLOCK = False
_C.MONITOR.MODULE_EFFECT.PROMPT_SELECTION_UNIFORM = False
_C.MONITOR.MODULE_EFFECT.PATCH_PROMPT_SELECTION_UNIFORM = False
_C.MONITOR.MODULE_EFFECT.PROMPT_VALUE_GLOBALIZE = False
_C.MONITOR.MODULE_EFFECT.LAYERWISE_PROMPT_READ_BLOCK = False
_C.MONITOR.MODULE_EFFECT.LAYERWISE_PROMPT_READ_LAYERS = []
_C.MONITOR.MODULE_EFFECT.PROMPT_CONTEXT_SWAP = False
_C.MONITOR.MODULE_EFFECT.PROMPT_CONTEXT_SWAP_LAYER = 9
_C.MONITOR.MODULE_EFFECT.PROMPT_CONTEXT_SWAP_SEED = 57721
_C.MONITOR.MODULE_EFFECT.INSTANCE_PROMPT_ZERO = False
_C.MONITOR.MODULE_EFFECT.DOMAIN_PROMPT_ZERO = False
_C.MONITOR.MODULE_EFFECT.BOTH_PROMPT_ZERO = False
_C.MONITOR.MODULE_EFFECT.INSTANCE_PROMPT_SWAP = False
_C.MONITOR.MODULE_EFFECT.INSTANCE_PROMPT_SWAP_SEED = 104729
_C.MONITOR.MODULE_EFFECT.PROMPT_VALUE_ZERO = False
_C.MONITOR.MODULE_EFFECT.ATTRIBUTE_CONCEPT_PATCH_BLOCK = False
_C.MONITOR.MODULE_EFFECT.ATTRIBUTE_CONCEPT_RANDOM_SEED = 271828
_C.MONITOR.MODULE_EFFECT.TRANSPORT_PATCH_BLOCK = False
_C.MONITOR.MODULE_EFFECT.TRANSPORT_RANDOM_SEED = 161803
_C.MONITOR.MODULE_EFFECT.ATTENTION_MEDIATION_GAMMA_ZERO = True
_C.MONITOR.MODULE_EFFECT.DEEP_RESIDUAL_ZERO = False
_C.MONITOR.MODULE_EFFECT.DEEP_RESIDUAL_SWAP = False
_C.MONITOR.MODULE_EFFECT.DEEP_RESIDUAL_SWAP_SEED = 130363
_C.MONITOR.PROMPT_RESIDUAL = CfgNode()
_C.MONITOR.PROMPT_RESIDUAL.ENABLE = True

_C.MODEL.ADAPTER = CfgNode()
_C.MODEL.ADAPTER.REDUCATION_FACTOR = 8
_C.MODEL.ADAPTER.STYLE = "Pfeiffer"

_C.SOLVER = CfgNode()
_C.SOLVER.LOSS_SEM_MED_WEIGHT = 0.0
_C.SOLVER.LOSS_SPV_WEIGHT = 0.0
_C.SOLVER.LOSS_ATTR_WEIGHT = 0.0
_C.SOLVER.LOSS_PROMPT_KL_WEIGHT = 0.0              # prompt distribution KL 权重；只约束 instance prompt 的 mu/logvar

_C.SOLVER.SEM_MED = CfgNode()
_C.SOLVER.SEM_MED.TARGET = "KpKv"                 # QpKv / QpQv / KpKv
_C.SOLVER.SEM_MED.METRIC = "cosine"                  # mse / kl / cosine
_C.SOLVER.SEM_MED.NORM = "softmax"                # first version only supports softmax
_C.SOLVER.SEM_MED.DETACH = "mediated"             # mediated / direct / none
_C.SOLVER.SEM_MED.LAYERS = []                     # empty means all shared layers

_C.SOLVER.SPV = CfgNode()
_C.SOLVER.SPV.COMPOSE = "prob"                    # prob (softmax(QsKp) @ softmax(Apv) 对齐 softmax(QsKv))/ raw_then_norm(softmax(QsKp @ Apv) 对齐 softmax(QsKv))
_C.SOLVER.SPV.TARGET = "QpKv"                     # QpKv / QpQv / KpKv
_C.SOLVER.SPV.METRIC = "kl"                       # mse / kl / cosine
_C.SOLVER.SPV.NORM = "softmax"                    # "none"raw affinity 直接相乘
_C.SOLVER.SPV.DETACH = "none"                     # mediated / direct / none
_C.SOLVER.SPV.LAYERS = []                         # empty means all shared layers

_C.SOLVER.ATTR = CfgNode()
_C.SOLVER.ATTR.METRIC = "mse"                     # 第一版只支持 mse：约束 ViT 交互后的 decoded attributes 接近真实类别属性

_C.SOLVER.RSIM = CfgNode()
_C.SOLVER.RSIM.ALIGN_MODE = "ar"                  # none / ar / cm
_C.SOLVER.RSIM.ALIGN_WEIGHT = 0.02

_C.SOLVER.DIAG = CfgNode()
_C.SOLVER.DIAG.SHUFFLE_RAW_TARGETS = False
_C.SOLVER.DIAG.STRICT_CHECKS = False
_C.SOLVER.OPTIMIZER = "adamw"
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.WEIGHT_DECAY = 0.0001
_C.SOLVER.PATIENCE = 300
_C.SOLVER.SCHEDULER = "cosine"          # 学习率随 epoch 怎么变化
_C.SOLVER.BASE_LR = 0.0005
_C.SOLVER.BIAS_MULTIPLIER = 1.
_C.SOLVER.WARMUP_EPOCH = 5
_C.SOLVER.TOTAL_EPOCH = 30
_C.SOLVER.LOG_EVERY_N = 111
_C.SOLVER.PROGRESS = CfgNode()
_C.SOLVER.PROGRESS.ENABLE = True
_C.SOLVER.PROGRESS.FORCE = False
_C.SOLVER.PROGRESS.NCOLS = 120
_C.SOLVER.PROGRESS.LEAVE = True
_C.SOLVER.PROGRESS.MININTERVAL = 0.5
_C.SOLVER.PROGRESS.MAXINTERVAL = 2.0
_C.SOLVER.PROGRESS.WRITE_STATE = True
_C.SOLVER.PROGRESS.STATE_EVERY_N = 5
_C.SOLVER.PROGRESS.STATE_MININTERVAL = 5.0
_C.SOLVER.SAVE_TRAINABLE_FINAL_CHECKPOINT = False
_C.SOLVER.TRAINABLE_FINAL_CHECKPOINT_NAME = "model_final_trainable.pth"
_C.SOLVER.STAGE2_CHECKPOINT_CELL_ID = ""
_C.SOLVER.DEBUG_GRAD_NORM = False
_C.SOLVER.DEBUG_TRACE_ONCE = False
_C.SOLVER.DEBUG_SHAPES = False
_C.SOLVER.EVAL_MODE = "zsl"


_C.SOLVER.VIS = CfgNode()
_C.SOLVER.VIS.ENABLE = False
_C.SOLVER.VIS.FINAL_ONLY = True
_C.SOLVER.VIS.EVERY_EPOCH = 1
_C.SOLVER.VIS.EPOCH_LIST = []
_C.SOLVER.VIS.SPLITS = ["test_unseen"]
_C.SOLVER.VIS.MAX_SAMPLES = 5
_C.SOLVER.VIS.CORRECT_SAMPLES = 3
_C.SOLVER.VIS.WRONG_SAMPLES = 2
_C.SOLVER.VIS.SAVE_RAW = True
_C.SOLVER.VIS.SAVE_IMAGES = True
_C.SOLVER.VIS.ROLLOUT = True
# BEGIN SEMANTIC_ABLATION_EXPERIMENT
_C.SOLVER.VIS.SEMANTIC_ABLATION = CfgNode()
_C.SOLVER.VIS.SEMANTIC_ABLATION.ENABLE = False
_C.SOLVER.VIS.SEMANTIC_ABLATION.DELTA_ASV = False
_C.SOLVER.VIS.SEMANTIC_ABLATION.ATTENTION_MASS = False
_C.SOLVER.VIS.SEMANTIC_ABLATION.DELTA_REFERENCE_SOURCE = "class_mean"
# END SEMANTIC_ABLATION_EXPERIMENT
_C.SOLVER.DBG_TRAINABLE = False

_C.DATA = CfgNode()
_C.DATA.NAME = "CUB"
_C.DATA.DATAPATH = "datasets/CUB/CUB_200_2011"
_C.DATA.FEATURE = "sup_vitb16_224"
_C.DATA.NUMBER_CLASSES = 200
_C.DATA.CLASS_WEIGHTS_TYPE = "none"
_C.DATA.CROPSIZE = 224
_C.DATA.BATCH_SIZE = 32
_C.DATA.NUM_WORKERS = 4
_C.DATA.PIN_MEMORY = True

_C.DATA.XLSA = CfgNode()
_C.DATA.XLSA.ENABLED = True
_C.DATA.XLSA.RES101_PATH = "datasets/xlsa17/xlsa17/data/CUB/res101.mat"
_C.DATA.XLSA.SPLIT_PATH = "datasets/xlsa17/xlsa17/data/CUB/att_splits.mat"
_C.DATA.XLSA.PROTOCOL_MODE = "dev"     #dev / final_zsl / final_gzsl
_C.DIST_INIT_PATH = "env://"


def get_cfg():
    """Get a copy of the default config."""
    return _C.clone()
