_BASE_: "B3-R2I-class-consistent.yaml"
OUTPUT_DIR: "output/b3_series/B3-R3I-partial-unfreeze"

MODEL:
  PROMPT:
    DISTRIBUTOR:
      DEEP_RESIDUAL:
        ARCHITECTURE_ID: "B3-R3I-partial-unfreeze"
        FREEZE_STATIC_PROMPT: false
        FREEZE_CLASSIFIER: true

SOLVER:
  STATIC_PROMPT_LR_MULTIPLIER: 0.1

